package net.cartola.domain;

/**
 * 01/11/2015 16:10:43
 * @author murilo
 */
public enum MercadoriaOrigem {
    
    NACIONAL,
    ESTRANGEIRA_ACAO_DIRETA,
    ESTRANGEIRA_ADQUIRIDO_MERCADO_INTERNO,
    NACIONAL_CONTEUDO_ADO_MAIOR_40,
    NACIONAL_CONFORMIDADE_PROCESSOS,
    NACIONAL_CONTEUDO_ADO_MENOR_40,
    ESTRANGEIRA_ACAO_DIRETA_CAMEX,
    ESTRANGEIRA_ADQUIRIDO_MERCADO_INTERNO_CAMEX,
    NACIONAL_CONTEUDO_ADO_MAIOR_70;
    
}
