package net.cartola.domain;

/**
 * 25/10/2015 00:48:47
 * @author murilo
 */
public enum PessoaContatoTipo {

    COMERCIAL, ADMINISTRACAO, PROPRIETARIO, COMPRAS, VENDEDOR, REPRESENTANTE, ASSISTENCIA_TECNICA, CONTAS_A_PAGAR, CONTAS_A_RECEBER, FINANCEIRO, MAE_OU_PAI, IRMAO, FILHO, PRIMO, TIO, CUNHADO, MECANICO, OUTROS;
}
