package net.cartola.domain;

public enum PessoaTelefoneTipo {

    PRINCIPAL, CELULAR, CELULAR_COMERCIAL, CELULAR_PESSOAL, PAGER, COMERCIAL, RESIDENCIAL, RECADOS, FAX, FAX_RESIDENCIAL, FAX_COMERCIAL, OUTROS;
}
